bind wlr_text_input_v3.h
swaywm/zig-wlroots pull request #16
Opened 2021-05-28 16:47 UTC by novakne

2021-05-28 18:12 UTC, ifreund requested changes

2021-05-28 18:12 UTC, ifreund commented on src/types/text_imput_v3.zig
> +    focused_surface: *wlr.Surface,
This one needs to be optional. In general, we need to go through most stored pointers to check if they are ever set to null.

2021-05-28 18:12 UTC, ifreund commented on src/types/text_imput_v3.zig
> +extern fn wlr_text_input_v3_send_enter(text_input: *wlr.TextInputV3, surface: *wlr.Surface) void;
This and the other `wlr_text_input_v3` functions should go inside the `TextInputV3` namespace.

2021-05-28 19:10 UTC, novakne commented on src/types/text_imput_v3.zig
> +    display_destroy: wl.Listener(*wl.Display),
Oh that's a difference with the main wlroots right? I think I read about it but forget about it after

2021-05-28 19:11 UTC, novakne commented on src/types/text_imput_v3.zig
> +    pub const State = extern struct {
Huh my brain died here or what.. sorry

2021-05-28 19:18 UTC, novakne commented on src/types/text_imput_v3.zig
> +    pub const State = extern struct {
oh wait they are here but I didn't close the State enum

2021-05-28 19:26 UTC, novakne commented
Well that's was a lot of errors, should be good now

2021-05-28 20:12 UTC, ifreund requested changes

2021-05-28 20:12 UTC, ifreund commented on src/types/text_imput_v3.zig
> +        };
This is a field, as is content_type and cursor_rectangle.
```suggestion
        surrounding: extern struct {
            text: ?[*:0]u8,
            cursor: u32,
            anchor: u32,
        },
```

2021-05-28 20:12 UTC, ifreund commented on src/types/text_imput_v3.zig
> +    }
there's no need for a wrapper here, just do 
```zig
pub const sendDone = wlr_text_input_v3_send_done;
```
The same goes for the other functions as well.

2021-05-28 20:12 UTC, ifreund commented on src/types/text_imput_v3.zig
> +    pub const Features = extern struct {
This struct has no fields, therefore it is a namespace and snake_case. The extern is also unnecessary.
```suggestion
    pub const features = struct {
```

2021-05-29 00:27 UTC, ifreund commented on src/types/text_imput_v3.zig
> +    pub const State = extern struct {
The fields of this struct are in the wrong order.

2021-05-29 06:15 UTC, novakne commented
damn, sorry for all this work on the review

2021-05-29 17:02 UTC, ifreund requested changes
I don't see any other issues, so with these last two fixes this should be good to merge.

2021-05-29 18:42 UTC, ifreund approved these changes
LGTM!

2021-05-29 18:42 UTC, merged

2021-05-29 19:01 UTC, novakne commented
Thanks for your patience, next time will be better :)