bind wlr_keyboard_shortcuts_inhibit_v1.h
swaywm/zig-wlroots pull request #25
Opened 2021-06-29 08:37 UTC by novakne

2021-07-07 14:00 UTC, novakne commented
Fix issues found by the test, should have tried this before pushing the rebase

2021-07-12 21:18 UTC, ifreund requested changes

2021-07-12 21:18 UTC, ifreund commented on src/types/keyboard_shortcuts_inhibit_v1.zig
> +    inhibitors: wl.list.Head(wlr.IdleInhibitorV1, "link"),
```suggestion
    inhibitors: wl.list.Head(wlr.KeyboardShortcutsInhibitorV1, "link"),
```

2021-07-12 21:18 UTC, ifreund commented on src/types/keyboard_shortcuts_inhibit_v1.zig
> +    global: ?*wl.Global,
```suggestion
    global: *wl.Global,
```

2021-07-13 08:10 UTC, ifreund approved these changes
LGTM, thanks!

2021-07-13 08:10 UTC, merged