Bind wlr_output_management_v1.h
swaywm/zig-wlroots pull request #4
Opened 2020-11-28 15:10 UTC by dominikh

2020-11-28 16:49 UTC, ifreund requested changes
This will be nice to have

2020-11-28 16:49 UTC, ifreund commented on src/types/output_management_v1.zig
> +        resource: *wl.Resource,
This can be null
```suggestion
        resource: ?*wl.Resource,
```

2020-11-28 16:49 UTC, ifreund commented on src/types/output_management_v1.zig
> +            return wlr_output_configuration_head_v1_create(config, output) orelse error.HeadCreateFailed;
https://github.com/swaywm/wlroots/pull/2501
```suggestion
            return wlr_output_configuration_head_v1_create(config, output) orelse error.OutOfMemory;
```

2020-11-29 02:05 UTC, dominikh commented on src/types/output_management_v1.zig
> +    resource: *wl.Resource,
Can this one be null then, too?

2020-11-29 09:49 UTC, ifreund commented on src/types/output_management_v1.zig
> +    resource: *wl.Resource,
Indeed

2020-11-29 14:17 UTC, ifreund approved these changes
LGTM, thanks!

2020-11-29 14:17 UTC, merged