Bind wlr_subsurface_from_wlr_surface and wlr_surface_is_subsurface
swaywm/zig-wlroots pull request #43
Opened 2022-03-20 01:56 UTC by dfangx

Required by https://github.com/riverwm/river/pull/568

2022-04-01 02:52 UTC, dfangx commented
@novakne could you give this a review?

2022-04-01 02:52 UTC, dfangx commented
@novakne could you give this a review?

2022-04-01 10:18 UTC, novakne commented
LGTM, although maybe I'll move `wlr_subsurface_from_wlr_surface` in Surface since it takes a Surface as argument. @ifreund would be the one who decides on this though.

2022-04-09 16:17 UTC, ifreund requested changes
Looks good to me aside from comment.

2022-04-09 16:17 UTC, ifreund commented on src/types/surface.zig
> +    extern fn wlr_subsurface_from_wlr_surface(surface: *Surface) *wlr.Subsurface;
>  Get a subsurface from a surface. Can return NULL if the subsurface has been destroyed.
```suggestion
    extern fn wlr_subsurface_from_wlr_surface(surface: *Surface) ?*wlr.Subsurface;
```

2022-04-12 09:36 UTC, merged